project:
  type: website
  output-dir: docs

website:
  title: "CleanEX"
  search: false
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: false
  navbar:
    right:
      - icon: envelope-fill
        href: mailto:mauro.maver@univr.it
    background: primary
  page-footer:
    right: "Creato da Mauro Maver"
    background: primary
    foreground: primary

format:
  html:
    smooth-scroll: true
    theme: Minty
    toc: false
    embed-resources: false

filters:
  - quarto-ext/shinylive

execute:
  freeze: auto

editor: source