project:
  type: website
  output-dir: docs
  
filters:
  - shinylive

website:
  title: "CleanEX"
  #description: "Descrizione..."
  search: false
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: false
  navbar:
    right:
      - icon: envelope-fill
        href: mailto:mauro.maver@univr.it
    background: primary
  page-footer: 
    right: "Creato da Mauro Maver" 
    background: primary
    foreground: primary

format:
  html:
    smooth-scroll: true
    theme: Minty
    css: styles.css
    toc: true
    toc-depth: 3
    embed-resources: false

editor: source

execute:
  freeze: auto # re-render only when source changes 

